### ISSUE TITLE
US1: Project Listing

### ISSUE THREAD

**Issue by ThysBat** [ThysBat/worldbuilding-tool#1]
## Value Proposition

As a User
I want to see an overview of my projects
so that I can get an overview about how many projects I already have.
​

## Description

![US1-project-listing](https://github.com/ThysBat/worldbuilding-tool/assets/96499440/8320a3a2-afea-40bc-a49f-95a8af2af7f0)

​
## Acceptance Criteria

- [ ] The headline is "Projects"
- [ ] projects are displayed as cards, sorted alphabetically
- [ ] the project cards include their project name
- [ ] the project cards are displayed in horizontally rows and slip into the next line if there is not enough space for another card
      ​

## Tasks

- [x] switch to a feature branch
- [x] add a headline
- [x] create a `ProjectsList` component
- [x] create a `ProjectCard` component
    - [x] add project name
- [x] create projects mock array
- [x] use `ProjectCard` component to display the projects in the `ProjectsList` component

**Comment by ThysBat** [comment]
I thought about that too. I just struggled a bit in general to separate each step and explain it separately. But I will give it a try! 🙂

**Comment by ThysBat** [comment]
I excluded the "create new project" function now. May this fit better as a US?

**Comment by FelineHuhn** [comment]
I think this change is great. I have some more suggestions now: 

The plus symbol for adding a new project should be removed, before the feature of adding a new project is create. 
And why is the template project visually represented differently to the others? Maybe this could be something to mention in the acceptance criteria? 
Perhaps the acceptance criteria should be more detailed in principle? You could add a few more steps like: 
- the headline is "Projects"
- the projects are displayed as cards (should the cards be sorted e.g. alphabetically/date of creation/...?)
- the project cards include their project name
- the cards are displayed in horizontally rows, and if there is not enough space, it slips into the next line

Maybe you could also need not only a `ProjectsList` component but also a `Project` component, or?

The tasks maybe could also be more specific like: 
- [ ] add a headline 
- [ ] create a `ProjectsList` component
- [ ] create a `Project` component 
  - [ ] add project name
- [ ] create projects mock array
- [ ] use `Project` component to display the projects in the `ProjectsList` component

**Comment by mbosselmann** [comment]
Hi David,
great job so far! 💪 I have some additional remarks for you to consider:

**Value Proposition**
**As a** User
**I want to** see an overview of my projects
**so that I can** easily switch between different themed projects.

- I like the first part of your value proposition, but I think that with the implementation of this user story the user cannot switch between projects as the user only gets an overview about the projects. My suggestion for a value proposition:

**As a** user
**I want to** see a list of all my pen and paper projects
**so that I can** get an overview about how many pen and paper projects I have

**Wireframe & Acceptance Criteria**
- I see that Feline recommend as title "Projects". This is fine, but you can also be more specific and write "Pen and Paper Projects" if you like. :)
- Otherwise I really like the acceptance criteria and your wireframe!

**Tasks**
- you can add that you need to create a feature branch (for you to remember). But is not a must. ;)

I hope this does help! Your first user story is almost ready! 💪 
Feel free to ask me if you have further questions. :)

**Comment by ThysBat** [comment]
Thank you Mareike for your recommendations! 🙂
I updated my value proposition, because you are right, I explained a feature I don't want to implement in the first step.
For now I would like to just write "Projects" in the heading since this app could be used for every aspect of writing and not only pen and paper.

**Comment by mbosselmann** [comment]
Hi David,
perfect! I just saw the word "Aventurien" and instantly thought that it must be a pen and paper projects app. ;) 

Your first user story is approved! 💪

**Comment by ThysBat** [comment]
Alright thank you! 😊 
I indeed played "Das Schwarze Auge" many years ago so it was intended to make a pen and paper reference 😄
