### ISSUE TITLE
US): Expand Articles

### ISSUE THREAD

**Issue by ThysBat** [ThysBat/worldbuilding-tool#15]
## Value Proposition

As a User
I want to be able to expand my articles
in order to shorten the time it needs to scroll through the articles.
​

## Description

![US9-expand-article](https://github.com/ThysBat/worldbuilding-tool/assets/96499440/5b6ed1d1-105f-48b9-8da1-1fbb0c880724)
​

## Acceptance Criteria

- [ ] a small icon indicates if an article is expandable
- [ ] upon clicking the icon, the article expands
- [ ] upon clicking the icon again, the article collapses
      ​

## Tasks

- [ ] switch too a feature branch
- [ ] add a button to `ArticleCard`
- [ ] the button toggles a state, that expands or collapses the article content

**Comment by CorneliusMoe** [comment]
Looks good, I love your project  😁

**Comment by ThysBat** [comment]
Thanks, I appreciate that! :D
