### ISSUE TITLE
US2: Add new project

### ISSUE THREAD

**Issue by ThysBat** [ThysBat/worldbuilding-tool#2]
## Value Proposition

As a User
I want to create a new project
so that I can save and create worlds/ projects with different themes (e.g. Steampunk, Sci-Fi)
​

## Description

![US2-add-new-project](https://github.com/ThysBat/worldbuilding-tool/assets/96499440/7f6909a4-1146-4d8e-9112-3cf0685eb326)

​
## Acceptance Criteria

- [ ] to create a new project you have to click a button
- [ ] the button is the first element of the project listing
- [ ] the button is styled like a `ProjectCard`
- [ ] the button click shall open an input element, overlaying the first row, expending the current card
- [ ] a project name is required to save a new project
- [ ] a close and a save button are displayed within, or right next to, the input element
- [ ] after saving the project, the user gets redirected to the dynamic `<projectname>` page
- [ ] on the `<projectname>` page the project name is displayed as heading
- [ ] a back button is displayed that redirects the user to the project listing
- [ ] on click on a `ProjectCard` the user gets redirected to its `<projectname>` page
      ​

## Tasks

- [x] switch to a new feature branch
- [x] add a styled button as the first element in the project listing, with the same styles as the `ProjectCard`
- [x] on button click, add a transition from the button to an input element for the projects name
- [x] add a cancel and save button for the input element
- [x] on click at the cancel button, close the input element
- [x] create a dynamic route structure for `<projectname>` pages -> [slug].js
- [x] display the projects name as heading
- [x] display a back button next to the heading
- [x] upon clicking the save button, when creating a new project, add the input value as project name to the projects mock data
- [x] then redirect the user to the dynamic `<projectname>` page
- [x] upon clicking the back button redirect the user to the project listing
- [x] wrap the `ProjectCard` component with a `Link` to redirect the user to the clicked `<projectname>` page

**Comment by sebastianwel** [comment]
Hey David, looks good to me so far! Only one tiny thing: 
What happens, when the user clicks on the +-button but then realizes he wants to go back to the previous page? Maybe it would make sense to add a "back"-button on the form-page. And one more suggestions to also add a subtitle like "add a new project", so that the page describes itself.

**Comment by ThysBat** [comment]
Thanks for the review!
The project navigation will be US3.
And at first I had a heading for the `new-project` page but I decided to not include it, because I want to make the look of this page the same as the actual `project` page.

**Comment by ThysBat** [comment]
So I updated the US now and I hope it makes more sense now without adding too much functionality... 🙂

**Comment by sebastianwel** [comment]
Looks good now I guess. Very detailed!
