### ISSUE TITLE
US3: Add a category

### ISSUE THREAD

**Issue by ThysBat** [ThysBat/worldbuilding-tool#3]
## Value Proposition

As a User  
I want to create several categories per project
so that I can create and manage different topics (e.g. culture, items)
​

## Description

![US3-add-category](https://github.com/ThysBat/worldbuilding-tool/assets/96499440/4d4d34e1-3bc9-4437-9385-04d16d91f8d3)

## Acceptance Criteria

- [ ] categories are displayed as cards, sorted alphabetically
- [ ] the category cards include their category name
- [ ] the category cards are displayed in horizontally rows and slip into the next line if there is not enough space for another card
- [ ] to create a new category you have to click a button
- [ ] the button is the first element of the category listing
- [ ] the button is styled like a category card
- [ ] the button click shall open an input element, overlaying the first row, expending the current card
- [ ] the styling is the same as the input element for [US2: Add new project](https://github.com/ThysBat/worldbuilding-tool/issues/2)
- [ ] a category name is required to save a new category
- [ ] after saving the category, the input element closes
- [ ] the new category is now displayed in the category list
- [ ] on click on a category card, the user is redirected to the `<categoryname>` page
- [ ] the styling is the same as the dynamic `<projectname>` page at [US2: Add new project](https://github.com/ThysBat/worldbuilding-tool/issues/2)
- [ ] the displayed back button redirects the user to the category listing

## Tasks

- [x] switch to a feature branch
- [x] create a `CategoriesList` component -> maybe you can refactor the `ProjectsListing` component to fit both needs
- [x] create a `CategoryCard` component -> maybe you can refactor the `ProjectCard` component to fit both needs
- [x] add category name
- [x] create category mock array
- [x] use `CategoryCard` component to display the categories in the `CategoriesList` component
- [x] add a styled button as the first element in the project listing, with the same styles as the ProjectCard
- [x] on button click, add a transition from the button to an input element for the projects name
- [x] add a cancel and save button for the input element
- [x] on click at the cancel button, close the input element
- [x] on click at the save button, close the input element and add the input value as category name to the categories mock data
- [x] create a dynamic route structure for <categoryname> pages -> [slug].js
- [x] display the category's name as heading
- [x] display a back button next to the heading
- [x] wrap the CategoryCard component with a Link to redirect the user to the clicked <categoryname> page
- [x] upon clicking the back button redirect the user to the category listing
