### ISSUE TITLE
US4: add entries

### ISSUE THREAD

**Issue by ThysBat** [ThysBat/worldbuilding-tool#4]
## Value Proposition

As a User
I want to create entries in every category
so that I can create some content and write down my ideas for each category
​

## Description

![US4-add-entry](https://github.com/ThysBat/worldbuilding-tool/assets/96499440/fd382443-2de4-4414-b499-995fcabda1e1)

## Acceptance Criteria

- [ ] entries are displayed as entry cards, sorted alphabetically
- [ ] the entry cards include their entry title
- [ ] the entry cards are displayed vertically
- [ ] to create a new entry you have to click a button
- [ ] the button is the first element of the entry listing
- [ ] the button is styled like an entry card
- [ ] an entry title is required to save a new entry
- [ ] the new entry is then displayed in the entry list
- [ ] on click on an entry card, the user is redirected to the `entry` page
- [ ] an `entry` page consists of the entry's title as heading and a button to add a new section and a back button
- [ ] the back button redirects the user to the entries listing
- [ ] the entry title is editable
- [ ] when adding a new section, a section card is created
- [ ] a section card consists of two inputs, one for the section card title and one for the description
- [ ] there shall be no need for a save button, every input is directly saved
      ​

## Tasks

- [x] create a feature branch
- [x] create an `EntryList` component
- [x] create an `EntryCard` component
- [x] create an entry mock array
- [x] add a styled button as the first element in the entries listing, with the same styles as the `EntryCard`
- [x] on button click, it changes to an input element for the entry's title
- [x] add a cancel and save button for the input element
- [x] on click on the cancel button, close the input element
- [x] on click on the save button, close the input element and add the input value as entry title to the entries mock data
- [x] create a dynamic route structure for `entry` pages
- [x] wrap the `EntryCard` component with a Link to redirect the user to the clicked `entry` page
- [x] display the entry's title as heading
- [x] display a back button next to the heading that redirects the user back to the category
- [x] create a `SectionListing`
- [x] create a `SectionCard`
- [x] add a button to add a new `SectionCard`
- [x] add a input for the sections's heading
- [x] add a textarea for the sections's description
- [x] add a "edit" button next to each inputs
- [x] every input is handled through a state, so no save button is needed

**Comment by ThysBat** [comment]
Thank you! I can recycle some points from earlier US because I have to do very similar tasks, that helps me alot 😅
