### ISSUE TITLE
US5: Add Subcategory

### ISSUE THREAD

**Issue by ThysBat** [ThysBat/worldbuilding-tool#8]
## Value Proposition

As a User
I want to create subcategories
so that I have a more detailed way to manage my entries.
​

## Description

![US5-add-subcategory](https://github.com/ThysBat/worldbuilding-tool/assets/96499440/ba444ff8-45c5-4030-a7f2-e2c892e31f33)
​

## Acceptance Criteria

- [ ] a list possible of subcategories is displayed in every category
- [ ] the styling and position is the same as the `CategoryList`
- [ ] You can add more subcategories the same way as in the `category` page
- [ ] the list of possible entries is displayed below the subcategories
- [ ] on click on a subcategory the user gets redirected to the `subcategory` page
- [ ] on the `subcategory` page the user can create entries the same way as in the `category` page
      ​

## Tasks

- [x] switch to a feature branch
- [x] create a `SubcategoriesList` component -> maybe you can refactor the `CategoriesList`
- [x] use `AddButtonList` to display possible subcategories
- [x] add a `handleSave` function that links the subcategories to the category they are nested in
- [x] use `EntryList` to display possible entries

**Comment by sebastianwel** [comment]
LGTM 🚀
