### ISSUE TITLE
US6: Delete projects, categories, entries

### ISSUE THREAD

**Issue by ThysBat** [ThysBat/worldbuilding-tool#9]
## Value Proposition

As a User
I want to delete Projects, Categories and Entries that I do not want anymore,
in order to have a clean folder structure with no unnecessary files
​

## Description

![US6-delete-projects-categories-entries](https://github.com/ThysBat/worldbuilding-tool/assets/96499440/d67bcbaa-cfb7-49cd-9796-05aa51393e09)

## Acceptance Criteria

- [ ] A delete button is displayed at the bottom left corner of the screen, or at the end of the content
- [ ] Upon clicking the delete button, a popup is displayed which the user has to confirm, in order to complete the deletion
- [ ] After deletion, the user gets redirected to the next higher folder level
      ​

## Tasks

- [x] create a `DeleteButton` component
- [x] write a delete function for deleting projects, categories and entries
- [x] use the `DeleteButton` in every component that can be deleted

**Comment by actyvystom** [comment]
A nice one! 👍🏻
